### PR TITLE
bnNext extension (includes #268 and #269)

### PR DESCRIPTION
**Pull request by Dendraspis**
#### Includes #268 and #269 

This basically extends #269 to give better and more intuitive usage possibilities.
Also solves the problem with pressed modifier keys and opening message boxes in between.
------

- Change bnSkip_Click() to bnNext_Skip() (see #268)
- Add possibility to add new jobs at specific position (see #269)
- Add ContextMenu to bnNext for all 4 possible options (to top/bottom / w/(o) opening Jobs)
- Change button text when modifier keys are pressed

### Rightclick:
StaxRipNext

--------

### Holding SHIFT:
StaxRipNext2

### CODE REVIEW

**Comment by Dendraspis** [comment]
Resolved 2 conflicts due to merged #268 and #269 via browser - hope formatting is okay.

**Comment by stax76** [comment]
As soon as I open a file I get a null ref exception here:

https://github.com/staxrip/staxrip/pull/276/files#diff-7829b16f29351f3711610270bd5d5ac5R6036

Does not matter how the file is opened.

Call Stack:

```
 	StaxRip.exe!StaxRip.MainForm.bnNextOnModifiers(Object sender, System.Windows.Forms.KeyEventArgs e) Line 6036	Basic
 	StaxRip.exe!StaxRip.MainForm.ButtonTextOnModifiers(Object sender, System.Windows.Forms.KeyEventArgs e) Line 6027	Basic
>	StaxRip.exe!StaxRip.MainForm.MainForm_Deactivate(Object sender, System.EventArgs e) Line 6015	Basic
 	[External Code]	
 	StaxRip.exe!StaxRip.MainForm.WndProc(System.Windows.Forms.Message m) Line 5378	Basic
 	[External Code]	
 	StaxRip.exe!StaxRip.TaskDialog(Of String).Show() Line 275	Basic
 	StaxRip.exe!StaxRip.MainForm.ShowOpenSourceDialog() Line 5131	Basic
 	[External Code]	
 	StaxRip.exe!StaxRip.CommandManager.Process(StaxRip.Command command, System.Collections.Generic.List(Of Object) params) Line 1085	Basic
 	StaxRip.exe!StaxRip.CommandManager.Process(String name, System.Collections.Generic.List(Of Object) params) Line 1073	Basic
 	StaxRip.exe!StaxRip.UI.CustomMenu.Process(StaxRip.UI.CustomMenuItem item) Line 254	Basic
 	StaxRip.exe!StaxRip.UI.CustomMenu.OnCommand(StaxRip.UI.CustomMenuItem item) Line 242	Basic
 	StaxRip.exe!StaxRip.UI.CustomMenu.MenuClick(Object sender, System.EventArgs e) Line 232	Basic
 	[External Code]	
 	StaxRip.exe!StaxRip.UI.MenuItemEx.OnClick(System.EventArgs e) Line 471	Basic
 	[External Code]	
 	StaxRip.exe!StaxRip.Startup.Main() Line 909	Basic
```

I've not much git experience you maybe I'm missing something.

**Comment by stax76** [comment]
I think it's because I have VS configured to break at exceptions.

**Comment by Dendraspis** [comment]
I fixed now 2 size values from the beta updater merge - seems like those merges are not 100% bullet-proof.

Although it's working, the problem is caused by `MainForm_Deactivate` which calls `ButtonTextOnModifiers(sender, Nothing)`.  Because `e` is `Nothing`, `If e.Modifiers.HasFlag(Keys.Shift) Then` throws an exception.
Because the `try{} catch{} finally{}` segment has to be there, this was the best solution for me - easy to read and well working.

But I can add a few if conditions to check if `e` and `e.Modifiers` are `Nothing`. 
Just give me a few hours to finish the running VS update .... ⏳  🙄 


💡  Sidenote:  Line 6040 seems useless with its command `bnNext.Text += ""`, but it was intended to add a down-arrow-icon or similar to indicate a context menu.
Haven't looked deeper into other buttons like 'When finished do', but if not needed it can be deleted.

**Comment by stax76** [comment]
I've merged it now with various changes. Using exceptions for control flow is not a good idea.

**Comment by Dendraspis** [comment]
Saw it ..... "some changes" sounds funny after looking at them.  😄  It's obvious that it's your project and you are more familiar with VB.NET than me.  😀 

The confound line with `ShowBold()` was a miserable mistake (lines 3956+) - online conflict resolving can be tricky.
But from now: Only 1 pending PR at the same time.  😠 

------------
> Using exceptions for control flow is not a good idea.

Of course, in general, but in my opinion at this specific situation it is okay. I won't create another PR for this, but I'm going to use my method (including some more conditions) for my personal usage. It has the benefit of handling modifier keys better/safer without side effects. Apart from the try-catch-finally usage, it's better to pass the modifier keys through to prevent that.

In addition you should consider calling `UpdateNextButton()`in `OnActivated(e As EventArgs)` (line 5951).

**Comment by stax76** [comment]
There is a feature to break on all exceptions, it can be enabled at:

Main Menu > Debug > Windows > Exception Settings

I've enabled all exceptions there in staxrip, it was always like this, downside is it breaks also when AbortException is used because the abort feature is exception based. I tried to exclude AbortException but it doesn't seem to work, it's probably a VS bug, maybe I should try to reproduce it on a test project and report it to MS.

Just checked mpv.net and there I don't have this break feature enabled, so I probably could also work well without it and might change it.

**Comment by Dendraspis** [comment]
I think the current code is absolutely okay - even better in some terms than my approach. 👍  So you can keep this setting enabled.  🙂 

I'll keep your solution and move to the next improvements.  😄 
Haven't used this settings ever, so sadly I can't give you any advice on this feature.

------

Btw:
> Using exceptions for control flow is not a good idea.

Look at MainForm.vs:AbortDueToLowDiskSpace()  😉

**Pull request merged**
