### PR TITLE
x265 preset values partly updated

### PR DESCRIPTION
**Pull request by Dendraspis**
Referenced issue #176

### CODE REVIEW

**Comment by Patman86** [comment]
Thx, I'm waiting for the merge process and update the settings.  There are more wrong parameters.

**Comment by Dendraspis** [comment]
No problem, just wanted to test this possibility mentioned by @stax76. 

> There are more wrong parameters.

I was afraid of that! At least my default *Slow* preset was alright. 🙄 
Thanks for the work!

**Comment by stax76** [comment]
Thanks. There are two methods that must be changed, one changes the value and the other the default value:

ApplyPresetValues
ApplyPresetDefaultValues

I've added the other.

**Comment by Dendraspis** [comment]
😮   Oh, good to know, I only saw one. Thanks for fixing the other one.

**Pull request merged**
