### PR TITLE
AvsResize website address and VS typo corrected

### PR DESCRIPTION
**Pull request by JJKylee**
Website: from Doom 9 to AviSynth Wiki
VS filter profiles: missing `clip = ` is added

### CODE REVIEW

**Comment by Dendraspis** [comment]
Looks like you've observed my instructions to @44vince44 how to edit files via browser.  😁

**Comment by JJKylee** [comment]
Yes, roughly.
Actually, I've not been doing that just because of my laziness. 😝 But bugging you and @stax76 for minor issues comes more cumbersome these days, so I did it this time. 😛

BTW, do you know of any method to keep my _forked_ repo on GitHub updated to the _original_ repo on GitHub? I did a search, but the only way I could find was via my local _cloned_ repo: pull from the original to the cloned repo, and then push to the forked repo. Isn't there a way to do it _online only_?

**Comment by Dendraspis** [comment]
> Actually, I've not been doing that just because of my laziness. 

😒   Okay, it's registered!

> BTW, do you know of any method to keep my forked repo on GitHub updated to the original repo on GitHub?

Nope, would also cause many issues when pushing.  😊 
The only fast solution, as long as you don't have changes or new branches:  delete and re-fork.

**Comment by JJKylee** [comment]
> The only fast solution, as long as you don't have changes or new branches: delete and re-fork.

I already did it two times when submitting the PRs. 😝

**Pull request merged**
