### PR TITLE
fix demux option with subtitles

### PR DESCRIPTION
**Pull request by Patman86**
after discussion here #190 , that's the right fix

### CODE REVIEW

**Comment by stax76** [comment]
But is there anything wrong at the moment?

**Comment by Patman86** [comment]
Yeah, see the issue/pull request #190

**Comment by stax76** [comment]
The current design is even if demuxing is disabled, audio tracks and subtitle tracks are still added, the source file is then directly the MKV/MP4 file instead of the demuxed files. Somebody who wants to disable subtitles or audio has to clear the Preferred Languages tracks. Being able to add audio tracks and subtitle tracks without demuxing is not a bad feature, there might be users interested in this feature. It's probably not particular intuitive, there are various things in staxrip that aren't very intuitive unfortunately. I can explain it in the docs. Maybe it's clearer to rename it from Preferred Languages to Used Languages and also describe this behavior in the tooltip.

**Comment by stax76** [comment]
I've documented it here:

https://staxrip.readthedocs.io/usage.html#demuxing

**Pull request closed without merging**
