### PR TITLE
Various Filter Updates

### PR DESCRIPTION
**Pull request by JJKylee**
- Add VS `AddGrain` plugin and filter profile
- Adjust `KNLMeansCL` strength values for `Strong`
- Add VS `AddBorders` filter profile
- Update VS `Bwdif` filter profile
- Add AVS `Bwdif` plugin and filter profile
- Add `FillBorders` plugins and filter profiles
- Adjust AVS `vsTTempSmooth` URLs
- Add AVS `Weave` filter profile
- Add VS `SeparateFields`, `Weave` filter profiles

All tested OK. 😊

### CODE REVIEW

**Comment by JJKylee** [comment]
[Commit c2a8fc6](https://github.com/staxrip/staxrip/pull/725/commits/c2a8fc6c7080476ecca92985e4cc464b01ff6547)

- Add `SelectEvery` filter profiles
- Update AVS `SelectRangeEvery` filter profile
- Rename VS filter menu item `Select` to `SelectField`

**Comment by JJKylee** [comment]
- Add VS `TemporalDegrain2` filter profile
- Add `DeRainbow` filter profiles and AVS script `DeRainbow.avsi`
- Add `DotKill` plugins and filter profiles

**Comment by JJKylee** [comment]
- Update `flash3kyuu_deband`, `f3kdb Neo` descriptions and download URLs
- Add AVS `vsCnr2` plugin and update `CNR2` filter profiles

**Comment by JJKylee** [comment]
- Update AVS `FFMS2`, `FFVideoSource` filter profiles to include VFR MKV timestamps file _automatically_
- Add AVS `TimecodeFPS` plugin and filter profile

**Comment by JJKylee** [comment]
- Update VS `ffms2` filter profile to include VFR MKV timestamps file _automatically_

**Comment by JJKylee** [comment]
- Update AVS `FFMS2`, `FFVideoSource`, VS `ffms2` filter profiles
  > Now these source filters _always_ work with a _timestamps file_. If the user sets the option to extract VFR MKV file timestamps file, these source filters will work with it. If not, they will generate their own timestamps file.

  > This is option must be activated if `TimecodeFPS` is to be used.

  > VS `ffms2` filter profile was updated in accordance with its AVS counterparts' profile updates.

- Update AVS `TimecodeFPS` filter profile
  > Since `TimecodeFPS` works _only with `FFMS2` or `FFVideoSource`_, its profile now issues an error when the source filter is not one of them.

**Comment by JJKylee** [comment]
[Commit 011ceea](https://github.com/staxrip/staxrip/pull/725/commits/011ceea27a1a30ecf448c47f1192b84ee4a00887)
- Add AVS `VfrToCfr` plugin and filter profile
- Recategorize/adjust AVS _VFR to CFR_ filters

**Comment by JJKylee** [comment]
[Commit bb69a62](https://github.com/staxrip/staxrip/pull/725/commits/bb69a62bd64bf807d42d04adfda1824d9c94f5d1)
- Changed source filter generated timecodes file name to _avoid autoload in `mkvmerge`_

**Comment by JJKylee** [comment]
Added filters:

`AnimeIVTC`(AVS), `GRunT`(AVS plugin), `Letterbox`(AVS/VS), `ReduceFlicker`(AVS), `Srestore`(AVS plugin), `TIVTC`(AVS), `VFRToCFR`(VS)

**Comment by JJKylee** [comment]
Added filters:

`Bifrost`(AVS/VS), `Checkmate`(AVS), `ChubbyRain2`(AVS), `DeFlicker`(AVS)

**Comment by Dendraspis** [comment]
Thanks a lot !!  👍 👍 👍

**Pull request merged**
