### PR TITLE
Allowed encode multi editions for one source video in batch mode.

### PR DESCRIPTION
**Pull request by Yuanuo**
Allows video files of different parameters/quality to be encoded during a batch process for the same video source file.

### CODE REVIEW

**Comment by stax76** [comment]
I don't understand what this patch is supposed to do. Changes look like they have potential to break things, code is very old, I don't remember much of it.

**Comment by Yuanuo** [comment]
Sorry, the code is not described in detail enough.


Simply put, the task names and temporary folder names used by each template remain different during the batch process so that there is no overwritten problem.


I want this need:
A file called "Production.MOV" video source file requires that it be encoded out of MP4 of different quality versions.
for example, one is 2Mbps and the other is 10Mbps.
I made two templates:
1) "Default Target Name" is "%source-name%-2Mbps";
2) "Default Target Name" is "%source-name%-10Mbps".

When I want to add this video file to the Batch task list at the same time, this requirement cannot be achieved due to the current implementation mechanism.
Because when you add a video source file, the task file created in the "Batch Projects" folder uses the name of the video source file, the configuration of the previous task is overwritten when you add it again.

The solutions provided in this Patch:
Name it according to the "Default Target Name" setup in the template's Options, including the task file name and the temp folder name during encoding.
1) When you add a video source file, the task file created in the Batch Projects folder is %source-name%-2Mbps (e.g. "Production.MOV-2Mbps").
When you add the video source file again after switching the template, it's "%source-name%-10Mbps" (e.g. "Production.MOV-10Mbps").
2) When actually encoding, "Temp Files Folder" will become "%source-name%-2Mbps_temp" (e.g. "Production.MOV-2Mbpss_temp") and "%source-name%-10Mbps_temp" (e.g. "Production.MOV-10Mbps_temp")

The final generated Mp4 file is still named as the default implementation.

This allows MP4 to be encoded sequentially with different parameters on a video source file.

**Comment by stax76** [comment]
A 'Batch Projects' folder is only used for 'File Batch' mode but why are you even using 'File Batch' mode? The whole idea of 'File Batch' mode is to batch process multiple source files with the same project template. If you switch project templates then you shouldn't use 'File Batch' mode.

**Comment by Yuanuo** [comment]
Well, thanks, this has solved my needs.

**Pull request closed without merging**
