### PR TITLE
Fix audio (and subtitle) cutting issues caused by ffmpeg upstream

### LINKED ISSUE #997: 2.15 cut audio not work
ffmpeg n6.0-8-g18dde8d4cf-20230319

C:\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe -f lavfi -i color=c=black:s=16x16:d=10779.602166667:r=59.940059940 -y -hide_banner -c:v copy "X:\WORK\859_temp\ID1 Japanese_458004649_458004650_cut_.avi"

mkvmerge cannot cut audio without video so an avi file has to be created

Input #0, lavfi, from 'color=c=black:s=16x16:d=10779.602166667:r=59.940059940':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: wrapped_avframe, yuv420p, 16x16 [SAR 1:1 DAR 1:1], 59.94 fps, 59.94 tbr, 59.94 tbn
Output #0, avi, to 'X:\WORK\859_temp\ID1 Japanese_458004649_458004650_cut_.avi':
  Metadata:
    ISFT            : Lavf60.3.100
  Stream #0:0: Video: wrapped_avframe, yuv420p, 16x16 [SAR 1:1 DAR 1:1], q=2-31, 59.94 fps, 59.94 tbr, 59.94 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded 

i change old ffmpeg from 2.14

fine work.

### PR DESCRIPTION
**Pull request by sheik124**
Closes #997 

Tested and confirmed working by manually performing the commands StaxRip uses to create the dummy/filler file and perform the subsequent cut.

### CODE REVIEW

**Comment by Discograp** [comment]
maybe the trim function is not the best

but this clipping cuts very synchronously

https://www.selur.de/

**Comment by Dendraspis** [comment]
@Discograp  What are you trying to tell us? It's great, that another app can handle this issue, but here we should discuss this pull request.

**Comment by Discograp** [comment]
instead of standard/basic delete, change to remove/cancel ??? Shutter encoder - so it can

remove - 00.00+45.00
remove - 48.00+53.12

**Comment by Discograp** [comment]
IMHO

1STEP - remove - 48.00+53.12
2STEP- CUT - 45.00+48.00

then it cuts without errors

**Comment by Dendraspis** [comment]
I think what you describe are UI related methods to select and keep/delete parts.
What sheik124 did is to finetune/fix the existing and working command to work (also) with ffmpeg v6. So I think this is the right way to go.

**Comment by Discograp** [comment]
cut function with deinterlacing
works superb!

**Pull request merged**
