### PR TITLE
Update various AVS packages URLs and info

### PR DESCRIPTION
**Pull request by JJKylee**
DAA3Mod, FineSharp, HQDeringmod, LSFmod, MAA2Mod, ResizeX, etc.

### CODE REVIEW

**Comment by JJKylee** [comment]
https://github.com/staxrip/staxrip/pull/689/commits/9105a0d4b3409300fbd221644762e00bc93c6a7d
⇒ Added `TTempSmooth` package for AVS along with its filters.

It's already in the program folder, but is missing from the _Apps Manager_.
This is to fix #690.

**Comment by JJKylee** [comment]
https://github.com/staxrip/staxrip/pull/689/commits/1e9ffa213c93045c363d098f81db99000d9c08cd
⇒ Added `vsTTempSmooth` AVS package that supports HBD.

Currently, `vsTTempSmooth` is not in the program tree, so we need to download and add the files from [here](https://github.com/Asd-g/AviSynth-vsTTempSmooth/releases).

**Comment by JJKylee** [comment]
https://github.com/staxrip/staxrip/pull/689/commits/944d47cf4deeb9fccbe708727bccdde9bb8c4c6f
⇒ Updated `MCTemporalDenoise` filter profiles for both AVS and VS.

**Comment by JJKylee** [comment]
https://github.com/staxrip/staxrip/pull/689/commits/89c2f82981d424a50e20526174f9b0f7c0131abe
⇒ Added `CASm` AVS package.

`CASm.avsi` is attached:
[CASm.zip](https://github.com/staxrip/staxrip/files/6422672/CASm.zip)

**Comment by Dendraspis** [comment]
@JJKylee 
Simme a signal when you're ready. 😁

**Comment by JJKylee** [comment]
I think that's it for now. 😄

**Pull request merged**
