### PR TITLE
align demux options for audio and subtitles

### PR DESCRIPTION
**Pull request by Patman86**
remove cases

### CODE REVIEW

**Comment by stax76** [comment]
Thanks for the Patch Patman, I review it in the next few days, working a little on some mpv.net issues currently.

**Comment by stax76** [comment]
Can you please describe what's currently wrong and what it fixes?

**Comment by Patman86** [comment]
There is nothing wrong! I only removed the case selection because it is not nacessary.

**Comment by stax76** [comment]
I don't really remember what this code is about, how it works and how difficult it is to find out.

This batch job issue from the forum yesterday was fixed by changing one line but I needed almost three hours to figure it out.

**Pull request closed without merging**
