### PR TITLE
Add missing FrameServer files

### PR DESCRIPTION
**Pull request by Dendraspis**
These files are missing in the repository, that are needed for building:

- VSHelper.h
- VSScript.h
- VapourSynth.h

Used the latest version.

### CODE REVIEW

**Comment by GregoryL77** [comment]
Hi. 
These are from Vapoursynth SDK. Could make problems after Vapour's updates.

**Comment by Dendraspis** [comment]
They are needed there to build the FrameServer solution. I think they are replaced at the same time, but somebody with the knowledge has to decide.

**Comment by stax76** [comment]
I'm not sure adding the header files to the projects is the best solution, the header files are part of the SDK and the SDK is included in the portable distribution so the header files are already in the Apps folder, problem is I missed making the path relative:

https://github.com/staxrip/staxrip/blob/master/FrameServer/FrameServer.vcxproj#L50

**Comment by Dendraspis** [comment]
Of course this is the right way!
I never would have thought somewhere absolute paths could be used, because too unusual.  🤔   But it explains why this issue occurs. 

Thanks for fixing!

**Pull request closed without merging**
