### PR TITLE
Add support for VapourSynth R55 and newer

### PR DESCRIPTION
**Pull request by DJATOM**
As Patman asked, I dug into it and spent a half day fighting with `getVSScriptAPI` procedure. For some reason `GetProcAddress` getting weird results (and heap corruption) if we load it into private member. So I decided to use slightly different approach (In fact it's a modification of previous method of loading procedures) and it worked.

As you see, COMPATBGR32 is nuked in APIv4, so we need libp2p plugin to make preview working again. `VideoScript.vb` edited to use it, but maybe you want to check for existence of plugin and warn user if he needs to install the plugin first. 

Feel free to edit that PR if needed.

### CODE REVIEW

**Comment by Patman86** [comment]
Hey, thanks @DJATOM. I tested your changes and yes it works. I think the changes can be accepted like this, except for small adjustments because of the plugin.

**Comment by Patman86** [comment]
@DJATOM:

I still found something. StaxRip has the possibility to use the portable version of Vapoursynth. Here an error appears during the initialization. With the installed version it works.

[Sample](https://a.uguu.se/ftWXvzRo.mp4)

**Comment by DJATOM** [comment]
[FrameServer.zip](https://github.com/staxrip/staxrip/files/8318257/FrameServer.zip)
does that work?

**Comment by Patman86** [comment]
> [FrameServer.zip](https://github.com/staxrip/staxrip/files/8318257/FrameServer.zip) does that work?

Nope.

**Comment by DJATOM** [comment]
Probably something weird on your end.
Try with my entire staxrip folder then: https://mega.nz/file/6wMGGTgR#-3LLzWnjV35ruzIP5vSms_YZsuGJfgQnfEA3oRGBK7A

**Comment by Patman86** [comment]
something is wrong with my Vaporsynth frame server files. It works with your files!

**Comment by jlw4049** [comment]
Will support for r55+ ever come?

**Comment by DJATOM** [comment]
Depends on maintainer decision 👐

**Comment by jlw4049** [comment]
@Dendraspis 😜

**Pull request closed without merging**
